In [1]:
import numpy as np
import tensorflow as tf
import torch
import matplotlib.pyplot as plt

2024-07-02 17:51:20.486757: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-02 17:51:20.509899: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-02 17:51:20.509929: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-02 17:51:20.509953: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-02 17:51:20.514836: I tensorflow/core/platform/cpu_feature_g

In [3]:
Basefolder = "../data/"
h_hat_pilot_tf=np.load(Basefolder+'h_hat_pilot_tf.npy') #(2, 1, 16, 1, 2, 128)
h_hat_pilot=np.load(Basefolder+'h_hat_pilot.npy') 
print(np.allclose(h_hat_pilot_tf, h_hat_pilot)) #True

inter_gather_ind_tf=np.load(Basefolder+'inter_gather_ind_tf.npy') #(1, 2, 14, 64)
inter_gather_ind=np.load(Basefolder+'inter_gather_ind.npy') 
print(np.allclose(inter_gather_ind_tf, inter_gather_ind)) #True

inputs_inter_tf=np.load(Basefolder+'inputs_inter_tf.npy') #(1, 2, 128, 1, 1, 1)
inputs_inter=np.load(Basefolder+'inputs_inter.npy') #(1, 2, 128, 1, 1, 1)
print(np.allclose(inputs_inter_tf, inputs_inter)) #True

outputs_inter_tf=np.load(Basefolder+'outputs_inter_tf.npy') #(1, 2, 14, 64, 1, 1, 1)
outputs_inter=np.load(Basefolder+'outputs_inter.npy') #(1, 2, 14, 64, 1, 1, 1)
print(np.allclose(outputs_inter_tf, outputs_inter)) #False

#tf.gather to extract specific indices from a single axis of a tensor.
#[num_tx, num_streams_per_tx, num_pilots, k, l, m]
#inputs_inter_tf(1, 2, 128, 1, 1, 1)  inter_gather_ind_tf: (1, 2, 14, 64)
outputs_tf = tf.gather(inputs_inter_tf, inter_gather_ind_tf, 2, batch_dims=2) #(1, 2, 14, 64, 1, 1, 1)
print(np.allclose(outputs_inter_tf, outputs_tf)) #True

True
True
True
False
True


2024-07-02 17:52:40.118656: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2024-07-02 17:52:40.118674: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: lkk-intel12
2024-07-02 17:52:40.118677: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: lkk-intel12
2024-07-02 17:52:40.118728: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: 535.183.1
2024-07-02 17:52:40.118736: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 535.183.1
2024-07-02 17:52:40.118738: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:309] kernel version seems to match DSO: 535.183.1


In [5]:
print(inter_gather_ind_tf[:,:,0,0])

[[0 1]]


In [8]:
tmp=inter_gather_ind_tf[:,:,:,0]
print(tmp.shape)
print(tmp)

(1, 2, 14)
[[[ 0  0  0  0  0  0  0 64 64 64 64 64 64 64]
  [ 1  1  1  1  1  1  1 65 65 65 65 65 65 65]]]


In [14]:
tmp=inter_gather_ind_tf[0,0,:,0]
print(tmp.shape)
print(tmp)

(14,)
[ 0  0  0  0  0  0  0 64 64 64 64 64 64 64]


In [16]:
tmp=inter_gather_ind_tf[0,1,:,0]
print(tmp.shape)
print(tmp)

(14,)
[ 1  1  1  1  1  1  1 65 65 65 65 65 65 65]


In [17]:
tmp=inter_gather_ind_tf[0,0,:,1]
print(tmp.shape)
print(tmp)

(14,)
[ 0  0  0  0  0  0  0 64 64 64 64 64 64 64]


In [11]:
tmp=inter_gather_ind_tf[:,:,:,1]
print(tmp.shape)
print(tmp)

(1, 2, 14)
[[[ 0  0  0  0  0  0  0 64 64 64 64 64 64 64]
  [ 1  1  1  1  1  1  1 65 65 65 65 65 65 65]]]


In [18]:
tmp=inter_gather_ind_tf[:,:,:,2]
print(tmp.shape)
print(tmp)

(1, 2, 14)
[[[ 2  2  2  2  2  2  2 66 66 66 66 66 66 66]
  [ 1  1  1  1  1  1  1 65 65 65 65 65 65 65]]]


In [6]:
print(inputs_inter_tf[:,:,0,0])

[[[[0.00039528]]

  [[0.        ]]]]


In [19]:
tmp=inputs_inter_tf[0,0,:,0,0,0]
print(tmp.shape)
print(tmp)

(128,)
[0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00039528 0.
 0.00039528 0.         0.00039528 0.         0.00

tf.gather: https://github.com/tensorflow/tensorflow/blob/v2.16.1/tensorflow/python/ops/array_ops.py#L4963-L4977
https://www.tensorflow.org/api_docs/python/tf/gather

The params may also have any shape. gather can select slices across any axis depending on the axis argument (which defaults to 0). Below it is used to gather first rows, then columns from a matrix:

In [20]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])
print(params.shape)
result = tf.gather(params, indices=[3,1]).numpy() #it means select row (3: 30.0, 31.0, 32.0), and row (1: 10.0, 11.0, 12.0)
print(result.shape)
print(result)




(4, 3)
(2, 3)
[[30. 31. 32.]
 [10. 11. 12.]]


In [21]:
result =tf.gather(params, indices=[2,1], axis=1).numpy() #it means select column 2 and column 1
print(result.shape)
print(result)

(4, 2)
[[ 2.  1.]
 [12. 11.]
 [22. 21.]
 [32. 31.]]


In [38]:
t=torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])
t.shape

torch.Size([4, 3])

In [39]:
#gather at dim=0, means select row
index_dim0 = torch.tensor([[0,1,3],
                           [3,1,2]]) #Shape is (2,3)
result = torch.gather(t, dim=0, index=index_dim0)
print(result.shape)
print(result)

torch.Size([2, 3])
tensor([[ 1,  5, 12],
        [10,  5,  9]])


My understanding: when index is 2-d, the output is the same shape as the index. dim=0 means the select row, the first index row [0,1,3] means select the index-mapped rows, while keep the order of the column as in the index. Output 0-col: select 0-row (1), 1-col: select 1-row (5), 2-col: select 3-row (12)

![tfgather1.png](../imgs/tfgather1.png)

In [41]:
t

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [40]:
#dim=1, select column
index_dim1 = torch.tensor([[0,2],
                           [1,0],
                           [0,2],
                           [1,0]]) #Shape is (4,2)
result=torch.gather(t, dim=1, index=index_dim1)
print(result.shape)
print(result)# [0,1]select the 0-col (1), and 2-col (3)



torch.Size([4, 2])
tensor([[ 1,  3],
        [ 5,  4],
        [ 7,  9],
        [11, 10]])


![tfgather2.png](../imgs/tfgather2.png)

The batch_dims argument lets you gather different items from each element of a batch.

Using batch_dims=1 is equivalent to having an outer loop over the first axis of params and indices:

In [29]:
params = tf.constant([
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]])
print(params.shape)
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
print(indices.shape)

(3, 5)
(3, 2)


In [30]:
result = tf.gather(params, indices, axis=1, batch_dims=1).numpy()
print(result.shape)
print(result)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [31]:
def manually_batched_gather(params, indices, axis, batch_dims=1):
  result = []
  for p,i in zip(params, indices):
    r = tf.gather(p, i, axis=axis-batch_dims)
    result.append(r)
  return tf.stack(result)
result =manually_batched_gather(params, indices, axis=1).numpy()
print(result.shape)
print(result)




(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [35]:
params = tf.constant([[
    [0, 0, 1, 0, 2],
    [3, 0, 0, 0, 4],
    [0, 5, 0, 6, 0]]])
print(params.shape)
indices = tf.constant([
    [2, 4],
    [0, 4],
    [1, 3]])
print(indices.shape)

(1, 3, 5)
(3, 2)


In [37]:
result =manually_batched_gather(params, indices, axis=1, batch_dims=2).numpy()
print(result.shape)
print(result)

(1, 3, 2)
[[[1 2]
  [0 4]
  [0 0]]]


In [45]:
import numpy as np

def gather_numpy(params, indices, axis):
    # Assuming params and indices are NumPy arrays
    # params: The tensor from which to gather values
    # indices: The indices to gather
    # axis: The axis along which to index
    
    # Use np.take_along_axis to gather values
    gathered_values = np.take_along_axis(params, indices, axis=axis)
    
    return gathered_values

# Example usage
params = np.array([[1, 2, 3], [4, 5, 6]])
print(params)
indices = np.array([[0, 2], [1, 0]])
print(indices)
result = gather_numpy(params, indices, axis=1)
print(result.shape)
print(result)


[[1 2 3]
 [4 5 6]]
[[0 2]
 [1 0]]
(2, 2)
[[1 3]
 [5 4]]


In [ ]:
def numpy_gather(params, indices, validate_indices=None, axis=None, batch_dims=0):
    gather_ind_nobatch = indices[0, 0] #ignore first two dimensions as batch (14, 64)
    outputs = np.take(params, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)

In [ ]:
inputs_inter_np = np.random.rand(1, 2, 128, 1, 1, 1)
inter_gather_ind_np = np.random.randint(0, 14, size=(1, 2, 14, 64))

In [ ]:
numpy_gather(inputs_inter_np, inter_gather_ind_np, validate_indices=None, axis=None, batch_dims=0)

In [60]:
def gather_numpy(inputs, indices, batch_dims=2):
    # Ensure the batch_dims is within the valid range
    if batch_dims < 0 or batch_dims >= len(inputs.shape):
        raise ValueError("Invalid batch_dims value")

    # Initialize the result tensor
    result = inputs.copy() #(1, 2, 128, 1, 1, 1)

    # Gather along each dimension
    # for dim in range(batch_dims, len(inputs.shape)): #2-6
    #     result = np.take(result, indices, axis=dim)

    #gather_ind_nobatch = indices[0, 0] #ignore first two dimensions as batch (14, 64)
    #result = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    gather_ind_nobatch = indices[0, 0] #ignore first two dimensions as batch (14, 64)
    result1 = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    gather_ind_nobatch = indices[0, 1] #ignore first two dimensions as batch (14, 64)
    result = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    result[0,0,:,:,:,:,:]=result1[0,0,:,:,:,:,:]

    return result

# Example usage
inputs_inter_np = np.random.rand(1, 2, 128, 1, 1, 1)
inter_gather_ind_np = np.random.randint(0, 14, size=(1, 2, 14, 64))
result = gather_numpy(inputs_inter_np, inter_gather_ind_np, batch_dims=2)

print("Result shape:", result.shape)  # Should be (1, 2, 14, 64, 1, 1, 1)

result_tf = tf.gather(inputs_inter_np, inter_gather_ind_np, 2, batch_dims=2) #(1, 2, 14, 64, 1, 1, 1)
print(np.allclose(result, result_tf)) #True

Result shape: (1, 2, 14, 64, 1, 1, 1)
True


In [102]:
def gather_numpy(inputs, indices, batch_dims=2):
    # Ensure the batch_dims is within the valid range
    if batch_dims < 0 or batch_dims >= len(inputs.shape):
        raise ValueError("Invalid batch_dims value")
    result = inputs.copy()
    # Gather along each dimension
    # for dim in range(batch_dims, len(inputs.shape)): #2-6
    #     result = np.take(result, indices, axis=dim)

    #gather_ind_nobatch = indices[0, 0] #ignore first two dimensions as batch (14, 64)
    #result = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    gather_ind_nobatch = indices[0, 0] #ignore first two dimensions as batch (14, 64)
    result1 = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    gather_ind_nobatch = indices[0, 1] #ignore first two dimensions as batch (14, 64)
    result = np.take(result, gather_ind_nobatch, axis=2) #(1, 2, 14, 64, 2, 1, 16)
    result[0,0,:,:,:,:,:]=result1[0,0,:,:,:,:,:]

    return result

# Example usage
inputs_inter_np = np.random.rand(1, 2, 128, 1, 1, 1)
inter_gather_ind_np = np.random.randint(0, 14, size=(1, 2, 14, 64))
result_np = gather_numpy(inputs_inter_np, inter_gather_ind_np, batch_dims=2)

print("Result shape:", result.shape)  # Should be (1, 2, 14, 64, 1, 1, 1)

result_tf = tf.gather(inputs_inter_np, inter_gather_ind_np, 2, batch_dims=2) #(1, 2, 14, 64, 1, 1, 1)
print(np.allclose(result_np, result_tf)) #True

Result shape: (1, 2, 14, 64, 1, 1, 1)
True


In [64]:
inputs_inter_np.shape

(1, 2, 128, 1, 1, 1)

In [72]:
batch_dims=2
axis = 2
shape1=inputs_inter_np.shape[0:batch_dims]
shape2=inputs_inter_np.shape[axis+1:]
shape3=inter_gather_ind_np.shape[batch_dims:]

In [76]:
newshape=shape1+shape3+shape2 #tuple add

In [77]:
newshape

(1, 2, 14, 64, 1, 1, 1)

In [73]:
shape2

(1, 1, 1)

In [67]:
shape1

(1, 2)

In [109]:
def gather_numpy2(inputs, indices, gt, axis=2, batch_dims=2):
    shape1=inputs.shape[0:batch_dims]
    shape2=inputs.shape[axis+1:]
    shape3=indices.shape[batch_dims:]
    newshape=shape1+shape3+shape2 #tuple add
    print("newshape:",newshape)
    output = np.zeros(newshape)

    loops=indices.shape[batch_dims-1] #2
    print("loops", loops)
    

    for dim in range(0, loops):
        gather_ind_nobatch = indices[0, dim]
        result = np.take(inputs, gather_ind_nobatch, axis)
        print("result:",result.shape)
        output[0,dim,:,:,:,:,:]=result[0,dim,:,:,:,:,:].copy()
        #result[0,0,:,:,:,:,:]=result1[0,0,:,:,:,:,:]
        print(np.allclose(result[0,dim,:,:,:,:,:], gt[0,dim,:,:,:,:,:])) #True
    

    return output

In [110]:
# Example usage
result_tf = tf.gather(inputs_inter_np, inter_gather_ind_np, 2, batch_dims=2) #(1, 2, 14, 64, 1, 1, 1)

inputs_inter_np = np.random.rand(1, 2, 128, 1, 1, 1)
inter_gather_ind_np = np.random.randint(0, 14, size=(1, 2, 14, 64))
result = gather_numpy2(inputs_inter_np, inter_gather_ind_np, result_tf, batch_dims=2)

print("Result shape:", result.shape)  # Should be (1, 2, 14, 64, 1, 1, 1)


print(np.allclose(result, result_tf)) #True

newshape: (1, 2, 14, 64, 1, 1, 1)
loops 2
result: (1, 2, 14, 64, 1, 1, 1)
False
result: (1, 2, 14, 64, 1, 1, 1)
False
Result shape: (1, 2, 14, 64, 1, 1, 1)
False


In [94]:
result_tf.shape

TensorShape([1, 2, 14, 64, 1, 1, 1])

In [52]:
print(np.allclose(result[0,0,:,:,:,:], result_tf[0,0,:,:,:,:]))

True


In [53]:
print(np.allclose(result[0,:,:,:,:,:], result_tf[0,:,:,:,:,:]))

False


In [54]:
print(np.allclose(result[:,0,:,:,:,:], result_tf[:,0,:,:,:,:]))

True


In [50]:
print(result[0,0,0,:,:,:])

[[[[0.06084636]]]


 [[[0.3385086 ]]]


 [[[0.15296875]]]


 [[[0.51489305]]]


 [[[0.0065215 ]]]


 [[[0.78731498]]]


 [[[0.36026969]]]


 [[[0.51489305]]]


 [[[0.0065215 ]]]


 [[[0.0065215 ]]]


 [[[0.0065215 ]]]


 [[[0.15296875]]]


 [[[0.36026969]]]


 [[[0.43951321]]]


 [[[0.3385086 ]]]


 [[[0.7891132 ]]]


 [[[0.0065215 ]]]


 [[[0.3385086 ]]]


 [[[0.43951321]]]


 [[[0.0065215 ]]]


 [[[0.15296875]]]


 [[[0.06084636]]]


 [[[0.0065215 ]]]


 [[[0.5466175 ]]]


 [[[0.78731498]]]


 [[[0.15296875]]]


 [[[0.28738122]]]


 [[[0.43951321]]]


 [[[0.15296875]]]


 [[[0.82570204]]]


 [[[0.51489305]]]


 [[[0.3385086 ]]]


 [[[0.78731498]]]


 [[[0.3385086 ]]]


 [[[0.78731498]]]


 [[[0.3385086 ]]]


 [[[0.3385086 ]]]


 [[[0.60340964]]]


 [[[0.15296875]]]


 [[[0.06084636]]]


 [[[0.5466175 ]]]


 [[[0.87904344]]]


 [[[0.06084636]]]


 [[[0.87904344]]]


 [[[0.82570204]]]


 [[[0.36026969]]]


 [[[0.43951321]]]


 [[[0.7891132 ]]]


 [[[0.78731498]]]


 [[[0.87904344]]]




In [51]:
print(result_tf[0,0,0,:,:,:])

tf.Tensor(
[[[[0.06084636]]]


 [[[0.3385086 ]]]


 [[[0.15296875]]]


 [[[0.51489305]]]


 [[[0.0065215 ]]]


 [[[0.78731498]]]


 [[[0.36026969]]]


 [[[0.51489305]]]


 [[[0.0065215 ]]]


 [[[0.0065215 ]]]


 [[[0.0065215 ]]]


 [[[0.15296875]]]


 [[[0.36026969]]]


 [[[0.43951321]]]


 [[[0.3385086 ]]]


 [[[0.7891132 ]]]


 [[[0.0065215 ]]]


 [[[0.3385086 ]]]


 [[[0.43951321]]]


 [[[0.0065215 ]]]


 [[[0.15296875]]]


 [[[0.06084636]]]


 [[[0.0065215 ]]]


 [[[0.5466175 ]]]


 [[[0.78731498]]]


 [[[0.15296875]]]


 [[[0.28738122]]]


 [[[0.43951321]]]


 [[[0.15296875]]]


 [[[0.82570204]]]


 [[[0.51489305]]]


 [[[0.3385086 ]]]


 [[[0.78731498]]]


 [[[0.3385086 ]]]


 [[[0.78731498]]]


 [[[0.3385086 ]]]


 [[[0.3385086 ]]]


 [[[0.60340964]]]


 [[[0.15296875]]]


 [[[0.06084636]]]


 [[[0.5466175 ]]]


 [[[0.87904344]]]


 [[[0.06084636]]]


 [[[0.87904344]]]


 [[[0.82570204]]]


 [[[0.36026969]]]


 [[[0.43951321]]]


 [[[0.7891132 ]]]


 [[[0.78731498]]]


 [[[0.879